name: wedding
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  jaspr: ^0.21.6
  jaspr_router: ^0.7.3

  # Firebase
  firebase_core: ^3.10.0
  firebase_core_web: ^2.18.3
  cloud_firestore: ^5.6.2

  # Web interop
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.2.3+1
  jaspr_builder: ^0.21.6
  jaspr_lints: ^0.5.1
  lints: ^5.0.0

jaspr:
  mode: client
  flutter_web_plugins: true

